# -*- coding: utf-8 -*-
"""Bank_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yroMlpHoY8KMXqCdy1UmBD5bn_yErPtC
"""

import pandas as pd

loans = pd.read_csv("loans.csv", low_memory=False)
customers = pd.read_csv("customers.csv", low_memory=False)
payments = pd.read_csv("payments.csv", low_memory=False)

date_cols = ["application_date", "disbursement_date"]

for col in date_cols:
    loans[col] = pd.to_datetime(loans[col], errors="coerce")

loans["loan_amount"] = pd.to_numeric(loans["loan_amount"], errors="coerce")

loans["interest_rate"] = loans["interest_rate"].astype(str).str.replace("%","")
loans["interest_rate"] = pd.to_numeric(loans["interest_rate"], errors="coerce")

import numpy as np

def clean_income(x):
    if pd.isna(x):
        return np.nan
    x = str(x).lower().replace(",","").replace("rs","").strip()
    if "k" in x:
        return float(x.replace("k","")) * 1000
    try:
        return float(x)
    except:
        return np.nan

customers["income"] = customers["income"].apply(clean_income)

mapping = {
    "salaried":"salaried",
    "salaride":"salaried",
    "self-employed":"self-employed",
    "self employedd":"self-employed"
}

customers["employment_type"] = customers["employment_type"].replace(mapping)

loans["product_type"] = loans["product_type"].replace({
    "educatioan": "education"
})

loans = loans.sort_values("disbursement_date").drop_duplicates("loan_id", keep="last")

loans.loc[loans["age_at_application"] > 100, "age_at_application"] = None

customers.loc[(customers["credit_score"] < 300) | (customers["credit_score"] > 850), "credit_score"] = None

loans["loan_amount"] = loans["loan_amount"].fillna(loans["loan_amount"].median())

loans["product_type"] = loans["product_type"].fillna("unknown")

customers["gender"] = customers["gender"].fillna("unknown")

loans.to_csv("loans_clean.csv", index=False)
customers.to_csv("customers_clean.csv", index=False)
payments.to_csv("payments_clean.csv", index=False)

"""# **MERGE DATASETS (Loans + Customers)**"""

df = loans.merge(customers, on="applicant_id", how="left")

df["loan_to_income"] = df["loan_amount"] / df["income"]

df["emi_to_income"] = df["emi"] / df["income"]

"""**APPLICANT AGE BUCKET**

"""

df["age_bucket"] = pd.cut(
    df["age_at_application"],
    bins=[0, 25, 35, 50, 100],
    labels=["young", "adult", "mid-age", "senior"]
)

df["credit_score_bucket"] = pd.cut(
    df["credit_score"],
    bins=[0, 600, 700, 800, 900],
    labels=["poor", "fair", "good", "excellent"]
)

late_payments = payments[payments["days_past_due"] > 0] \
                .groupby("loan_id")["days_past_due"] \
                .count().reset_index().rename(columns={"days_past_due":"late_payment_count"})

max_dpd = payments.groupby("loan_id")["days_past_due"] \
                 .max().reset_index().rename(columns={"days_past_due":"max_dpd"})

payments["on_time"] = payments["days_past_due"].apply(lambda x: 1 if x == 0 else 0)

ontime_ratio = payments.groupby("loan_id")["on_time"].mean() \
                       .reset_index().rename(columns={"on_time":"on_time_payment_ratio"})

df = df.merge(late_payments, on="loan_id", how="left")
df = df.merge(max_dpd, on="loan_id", how="left")
df = df.merge(ontime_ratio, on="loan_id", how="left")

df["vintage_days"] = (pd.Timestamp("today") - df["disbursement_date"]).dt.days

df["high_risk_flag"] = (
    (df["loan_to_income"] > 8) |
    (df["emi_to_income"] > 0.5) |
    (df["credit_score"] < 600) |
    (df["max_dpd"] > 60)
).astype(int)

df.to_csv("final_feature_engineered_dataset.csv", index=False)

"""# **EDA (Exploratory Data Analysis)**"""

df["default_flag"].mean()

df["loan_amount"].describe()

df["credit_score"].describe()

df.groupby(pd.qcut(df['loan_amount'], 10, duplicates='drop'))['default_flag'].mean()

df.groupby(pd.qcut(df["income"], 10))["default_flag"].mean()

df.groupby(pd.qcut(df["loan_to_income"], 10))["default_flag"].mean()

df.groupby("credit_score_bucket")["default_flag"].mean()

df.groupby("age_bucket")["default_flag"].mean()

df.groupby(pd.qcut(df["emi_to_income"], 10))["default_flag"].mean()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load final cleaned + feature engineered dataset
df = pd.read_csv("final_feature_engineered_dataset.csv", low_memory=False)

df.head()

print("Shape:", df.shape)
print("\nColumns:\n", df.columns)
print("\nMissing Values:\n", df.isnull().sum())
df.info()

default_rate = df['default_flag'].mean()
print("Default Rate: ", round(default_rate * 100, 2), "%")

df['loan_amount'].describe()

df['income'].describe()

df['credit_score'].describe()

df['emi_to_income'].describe()

plt.figure(figsize=(10,5))
sns.histplot(df['loan_amount'], bins=50, kde=True)
plt.title("Loan Amount Distribution")
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(df['income'], bins=50, kde=True)
plt.title("Income Distribution")
plt.show()

loan_default = df.groupby(pd.qcut(df['loan_amount'], 10, duplicates='drop'))['default_flag'].mean()
print(loan_default)

income_default = df.groupby(pd.qcut(df['income'], 10))['default_flag'].mean()
income_default

lti_default = df.groupby(pd.qcut(df['loan_to_income'], 10))['default_flag'].mean()
lti_default

emi_inc_default = df.groupby(pd.qcut(df['emi_to_income'], 10))['default_flag'].mean()
emi_inc_default

df.groupby('credit_score_bucket')['default_flag'].mean()

df.groupby('age_bucket')['default_flag'].mean()

df.groupby('product_type')['default_flag'].mean()

df.groupby(pd.qcut(df['late_payment_count'], 10, duplicates='drop'))['default_flag'].mean()

df.groupby(pd.qcut(df['max_dpd'], 10, duplicates='drop'))['default_flag'].mean()

plt.figure(figsize=(15,8))
sns.heatmap(df.corr(numeric_only=True), annot=False, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

print("\n🔹 DEFAULT RATE:", round(default_rate*100, 2), "%")

print("\n🔹 Highest Risk Loan Amount Segment:\n", loan_default.tail(1))

print("\n🔹 Highest Risk Income Segment:\n", income_default.tail(1))

print("\n🔹 Highest Risk Loan-to-Income Segment:\n", lti_default.tail(1))

print("\n🔹 Highest Risk EMI-to-Income Segment:\n", emi_inc_default.tail(1))

print("\n🔹 Credit Score Bucket Risks:\n", df.groupby('credit_score_bucket')['default_flag'].mean())

print("\n🔹 Product Type Risks:\n", df.groupby('product_type')['default_flag'].mean())

print("Shape:", df.shape)
print("\nColumns:\n", df.columns)
print("\nMissing Values:\n", df.isnull().sum())
df.info()